# NumPy Library


NumPy is short for Numerical Python, is a powerful library in Python used for numerical computing.
NumPy is used for working with arrays.
It provides support for arrays, matrices, and many mathematical functions to operate on these data structures.
NumPy is an essential library for scientific computing in Python.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.



In [1]:
# Import NumPy
# Once NumPy is installed, import it in your applications by adding the import keyword:
import numpy as np

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
# creating 1D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [5]:
# Array Operations
arr = np.array([1, 2, 3, 4, 5])

# Addition
print(arr + 10)

# Multiplication
print(arr * 2)

# Element-wise square
print(arr ** 2)


[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [6]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [7]:
#Access Array Elements

#Get the first element from the following array:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])

#Get third and fourth elements from the following array and add them.
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] , arr[3])

1
3 4


In [8]:
# Access 2-D Arrays
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [9]:
# Indexing and Slicing

# Accessing Elements

#Get the first element from the following array:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])

#Get third and fourth elements from the following array and add them.
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] , arr[3])

# Accessing a slice
print(arr[1:4])


1
3 4
[2 3 4]


In [10]:
# Negative Indexing
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [15]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [16]:
arr = np.array([1, 2, 3, 4,"a",])
print(arr)
print(arr.dtype)

['1' '2' '3' '4' 'a']
<U11


In [27]:
# Make a copy, change the original array, and display both arrays:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [28]:
# VIEW:
#Example
#Make a view, change the original array, and display both arrays:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [29]:
#Shape of an Array
#The shape of an array is the number of elements in each dimension
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [30]:
# Reshaping arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
# Iterating Arrays
#If we iterate on a 1-D array it will go through each element one by one.
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
    print(x)


1
2
3


In [32]:
#Iterate on the elements of the following 2-D array:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)


[1 2 3]
[4 5 6]


In [34]:
# Iterate on each scalar element of the 2-D array:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)
 

1
2
3
4
5
6


In [35]:
# Iterating Arrays Using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)


1
2
3
4
5
6
7
8


In [36]:
#filter array
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [37]:
#Split the array in 3 parts:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
